version: 2
jobs:
  build:
    docker:
      - image: vvakame/review:3.0
    steps:
      - checkout
      - run: |
          git submodule sync
          git submodule update --init
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Setup
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Build PDF
          command: npm run pdf
      - store_artifacts:
          path: ./articles/apollo-swamped-book.pdf
          destination: apollo-swamped-book.pdf
